### ISSUE TITLE
[Request] Add support for css selectors

### ISSUE THREAD

**Issue by pgroot91** [SideeX/sideex#13]
It seems that the CSS selectors are not supported in SideeX. Please add support for css selectors in SideeX.

E.g. css=button:contains("Install SideeX")

**Element is not found**

**Comment by shinjielee** [comment]
Got it. Thanks for your feedback. We'll check it.

**Comment by shinjielee** [comment]
Bug fixed. CSS selectors are supported in latest published version 2.3.4. Thanks again for your feedback.
