### ISSUE TITLE
How to disable a reload page on playback?

### ISSUE THREAD

**Issue by alex4200** [SideeX/sideex#32]
I recorded some actions on a webpage with sideex, after I loaded something in the webpage. 

However, when playing back the recordings sideex seems to reload the page, removing required information, and the test cannot run anymore. 

How can I disable the page reload? I just want the playback of what I recorded, nothing more. I did not record a reload of the page.

**Comment by shinjielee** [comment]
If the first command of your recorded test case is “open”, remove the command. The open command will reload the web page.

By the way, SideeX 3 was released. Check it out here: https://sideex.io

SideeX Team

**Comment by alex4200** [comment]
Yes, that is the solution! Now that is the tool I can use. Thanks a lot!
