### ISSUE TITLE
type does not work

### ISSUE THREAD

**Issue by pure1234** [SideeX/sideex#4]
您好，
因您文章受用良深，請教您一問題如附檔視訊，
環境為FF54&SideeX is an extended version of Selenium IDE，
CLICK指令可點到輸入欄位之ID，可是相同欄位相同ID，TYPE指令卻是未見任何動作，也就是未自動打字，WHY?
麻煩您了

**Comment by shinjielee** [comment]
我已看過附檔視訊，但由於無法實際施測於你的系統上，所以無法確定是否為type指令的bug。你可嘗試使用SideeX 2 for Chrome來試試看是否仍遭遇到此問題，下載網址為https://goo.gl/w3aZ2x。

若你能讓此系統頁面(或部分頁面)提供給我們進行測試的話，相信一定能讓我們加速解決此問題，謝謝你的回報!!

**Comment by xdennisx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Also, in terms of the testing assertions, the command VerifyTextPresent would be a lovely addition, If we could have the negative assertions/verifications, (AssertNot) that would also be amazing.](https://trello.com/c/GK4JRW64/51-also-in-terms-of-the-testing-assertions-the-command-verifytextpresent-would-be-a-lovely-addition-if-we-could-have-the-negative-a)

**Comment by shinjielee** [comment]
已於您的來信中解決。
