### ISSUE TITLE
Pressing delete while editing text also deletes the rule

### ISSUE THREAD

**Issue by e02d96ec16** [SideeX/sideex#5]
Please allow to use the delete key _while_ editing, without fear it is going to also delete the rules.
I often edit the values of those fields to tweak them.

### Expected

Pressing delete while editing text in a field, should only delete the text in that field (i.e. the usual behaviour).

### Actual 

Pressing delete while editing text in a field will also delete rules.

**Comment by shinjielee** [comment]
Thanks for your feedback. We've fixed it. The hot fix will be included in the upcoming release version.

**Comment by e02d96ec16** [comment]
I assume it is bd7d717. Thanks!

Any idea when the next version hits?

**Comment by shinjielee** [comment]
Version 2.3.1 has been released. The hotfix is included.
