### ISSUE TITLE
pause command completes immediatly instead of sleeping the requested time

### ISSUE THREAD

**Issue by trendzetter** [SideeX/sideex#6]
### Scenario:
1. Record a test
2. Add a command somewhere in your test so you can see how long your command takes to execute
3. Set the command to pause and the value to 30000

### Expected result:
The addtional command adds 30 seconds to my test at the step I inserted it.

### Actual result:
The pause is finished immediately but the log prints: 
[info] Executing: | pause | 30000 | |

**Comment by shinjielee** [comment]
Are you using SideeX 2 for Chrome? 

It seems you set TARGET to 30000, not set VALUE to 30000. Please  keep TARGET left blank and set VALUE to 30000, and try it again on SideeX 2 for Chrome.

Let us know if you still have the problem. Thanks.

**Comment by trendzetter** [comment]
The issue is resolved by using the value field instead of target. My mistake. It could be useful to warn if invalid parameters are used.
