### ISSUE TITLE
[Future Request] preprocess Target value

### ISSUE THREAD

**Issue by samitani** [SideeX/sideex#7]
Currently, the Value be pre-processed, so Step2 is work fine.
but, the Target not be pre-processed, so Step1, Step3 could not be done.

What i want:
1. store random string into $my_value to avoid duplicate 
2. type $my_value into some input fields and submit it
3. find the target which link name is $my_value and click it

Thank you for develop SideeX.

**Comment by shinjielee** [comment]
Could you please provide us the test script or screenshot for more detail? It would be of a great help to debug. 

The following is an example of using the store command. FYR.

![screenshot 2017-11-13 11 12 00](https://user-images.githubusercontent.com/9052880/32708204-99b035de-c863-11e7-8231-dc006e469994.png)

**Comment by shinjielee** [comment]
I would close the issue. You are welcome to reopen it.

**Comment by samitani** [comment]
sorry, late response.
this screen shot is what i do on selenium IDE. I would like to use javascript and variables for Target field.

![image](https://user-images.githubusercontent.com/2655102/32815357-045face0-c9f7-11e7-8e23-279a6f7e4eec.png)

**Comment by shinjielee** [comment]
Thanks. We are trying to solve it.

**Comment by shinjielee** [comment]
Bug fixed. Please upgrade to SideeX 2.3.2 published on Chrome web store. Please let me know if this issue is solved. Thanks.

**Comment by samitani** [comment]
It's works fine.
I have completed migration to SideeX from Selenium IDE. Thank you :smile:

**Comment by shinjielee** [comment]
Cheers! Feel free to tell us if you have any other problems.
