### ISSUE TITLE
selectFrame tiemouts in CKEditor formfield

### ISSUE THREAD

**Issue by Elettrotecnica** [SideeX/sideex#8]
I am recording test cases on an application that is using CKeditor in its richtext fields. Interaction involves entering the field, writing a test phrase and save by clicking a button. 

When replaying interaction this happens: frame for ckeditor is selected, text is enetered correctly, then replay hangs on command to leave ckeditor frame: "selectFrame relative=parent"

Attached is a screenshot of the replay
![issue](https://user-images.githubusercontent.com/3331940/33280411-445d9028-d3a2-11e7-8e71-2bfb23dfa603.png)

Many thanks for any feedback on this and keep up the good work!

**Comment by LinYunWen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [selectFrame on CKEditor error](https://trello.com/c/qghY89pz/50-selectframe-on-ckeditor-error)

**Comment by shinjielee** [comment]
Got it. We will take a look. Thanks for your feedback.

**Comment by shinjielee** [comment]
Fixed. Please check out the latest version.

**Comment by Elettrotecnica** [comment]
Current version works fine! Many thanks!

**Comment by baseemas** [comment]
I'm facing the above issue with latest version 2.3.4
![image](https://user-images.githubusercontent.com/48471350/54187378-11824f00-44b6-11e9-9f25-109e93e993d7.png)
