### ISSUE TITLE
script format

### ISSUE THREAD

**Issue by panpepson** [SideeX/sideex#9]
Hi, 

Is it possible to write a script in the editor and later add it to sidesx? If so, which format?

**Comment by shinjielee** [comment]
The script format is in html. You can 
1. record something and save it into a file.
2. open the file in a text editor and start to modify/edit it. 
3. load the file back to SideeX and run it

**Comment by panpepson** [comment]
ok thx

**Comment by shinjielee** [comment]
No problem!
